# NPCsMissions
# Version: beta
# Author: Ulrich (J4g3rNuBz)
#
# Do NOT use : in the text messages.
# You can use formatting codes (https://minecraft.gamepedia.com/Formatting_codes)
# Do not change the label <name_of_the_npc> (more will be added), you can delete it.
# 
# The command /reload it's not soported yet.
#
# Permissions:
# /createNPC: NPCsMissions.create
# /moveNPCHere: NPCsMissions.movehere
# /removeNPC: NPCsMissions.remove
# /renameNPC: NPCsMissions.rename
# Select an NPC: NPCsMissions.select (You have to use a diamond axe in the main hand and right click the NPC)
#

npc-message: 
  - 'Hey! I am &l&9<name_of_the_npc>, &fhere is your mission'
  - '&8Mission &csample' 
  - '&6Good &cluck'
  
dont-have-permission: '&c&lYou do not have permission to run this command!'

npc-created: '&c&lNPC Created! :)'

npc-moved: '&c&lNPC moved!'

npc-removed: '&c&lNPC removed!'

npc-renamed: '&c&lNPC renamed!'
